name: notification_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  path_provider: ^2.1.3
  # todo-00-init-01: add dependency
  flutter_timezone: ^1.0.8
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
