// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xa369lW6daiDPDo53cmnIacKbgwt5fQ',
    appId: '1:1077531466593:web:4d0a467182877289604320',
    messagingSenderId: '1077531466593',
    projectId: 'dicoding-chatting',
    authDomain: 'dicoding-chatting.firebaseapp.com',
    databaseURL: 'https://dicoding-chatting.firebaseio.com',
    storageBucket: 'dicoding-chatting.appspot.com',
    measurementId: 'G-2E8PYT4GQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1QvXga0nrjaVeNWyoi0e0_rM_tT9n8Q',
    appId: '1:1077531466593:android:3f5851ddec714788604320',
    messagingSenderId: '1077531466593',
    projectId: 'dicoding-chatting',
    databaseURL: 'https://dicoding-chatting.firebaseio.com',
    storageBucket: 'dicoding-chatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbEbxAtz8P_B7Z0l_FnCuKtRL3EpyJMg',
    appId: '1:1077531466593:ios:941941579a0c5aed604320',
    messagingSenderId: '1077531466593',
    projectId: 'dicoding-chatting',
    databaseURL: 'https://dicoding-chatting.firebaseio.com',
    storageBucket: 'dicoding-chatting.appspot.com',
    iosClientId: '1077531466593-ss8pltfla3859emqmhrju6i03r4cnst2.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
